server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB

  datasource:
    url: jdbc:mysql://localhost:3306/homedrive?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

file:
  base-dir: /home/laphayen/homedrive/uploads
  use-hash: true
  hash-type: SHA-256
  chunk-temp-dir: /home/laphayen/homedrive/temp/chunks
  max-chunk-size: 10MB

jwt:
  secret: your-very-secret-key-should-be-at-least-32-characters
  access-token-validity-ms: 3600000         # 15?
  refresh-token-validity-ms: 604800000      # 7?

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
